apiVersion: v1
kind: ConfigMap

metadata:
  name: finops-api-config
  namespace: finops

data:
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  WEB_CORS_ORIGINS: https://app.sniper541.com,http://localhost:5173
