apiVersion: apps/v1
kind: Deployment

metadata:
  name: finops-bot
  namespace: finops

spec:
  replicas: 1

  selector:
    matchLabels:
      app: finops-bot

  template:
    metadata:
      labels:
        app: finops-bot

    spec:
      securityContext:
        runAsNonRoot: true
        fsGroup: 10002
        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: finops-bot
          image: ghcr.io/sniper541/homelab-finops/finops-bot:7ab51ed7605b9234fcca6a6aba97553992848fe4
          imagePullPolicy: Always

          env:
            - name: TELEGRAM_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: finops-bot-secret
                  key: TELEGRAM_BOT_TOKEN

            - name: FINOPS_API_URL
              value: "https://api.sniper541.com"

            - name: TELEGRAM_PROXY_URL
              value: "socks5://127.0.0.1:1080"

          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"

          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 10001
            capabilities:
              drop:
                - ALL

        - name: ssh-proxy
          image: ghcr.io/sniper541/homelab-finops/finops-ssh-proxy:7ab51ed7605b9234fcca6a6aba97553992848fe4
          imagePullPolicy: Always

          args:
            - "-N"
            - "-D"
            - "0.0.0.0:1080"
            - "-i"
            - "/ssh/id_ed25519"
            - "-o"
            - "BatchMode=yes"
            - "-o"
            - "StrictHostKeyChecking=no"
            - "-o"
            - "ExitOnForwardFailure=yes"
            - "-o"
            - "ServerAliveInterval=30"
            - "-o"
            - "ServerAliveCountMax=3"
            - "finops-proxy@89.110.67.219"

          volumeMounts:
            - name: proxy-ssh-key
              mountPath: /ssh
              readOnly: true

          resources:
            requests:
              cpu: "20m"
              memory: "32Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"

          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10002
            runAsGroup: 10002
            capabilities:
              drop:
                - ALL

      volumes:
        - name: proxy-ssh-key
          secret:
            secretName: finops-bot-proxy-ssh
            defaultMode: 0440