FROM alpine:3.22

RUN apk add --no-cache openssh-client \
    && addgroup -g 10002 finops-proxy \
    && adduser -D -u 10002 -G finops-proxy finops-proxy \
    && mkdir -p /home/finops-proxy/.ssh \
    && chown -R 10002:10002 /home/finops-proxy

USER 10002

ENTRYPOINT ["ssh"]
