apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: finops-auth-routing
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sniper541/homelab-finops.git
    targetRevision: main
    path: infrastructure/keycloak
    directory:
      include: finops-origin.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
