apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://grafana-community.github.io/helm-charts
      chart: grafana
      targetRevision: 13.2.7
      helm:
        releaseName: grafana
        valueFiles:
          - $values/infrastructure/observability/grafana-values.yaml
    - repoURL: https://github.com/sniper541/homelab-finops.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
