apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-ui
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/sniper541/homelab-finops.git
    targetRevision: main
    path: infrastructure/kafka-ui

  destination:
    server: https://kubernetes.default.svc
    namespace: kafka

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=false
