apiVersion: v1
kind: ConfigMap
metadata:
  name: finops-kafka-metrics
  namespace: kafka
data:
  kafka-metrics-config.yml: |
    lowercaseOutputName: true
    rules:
      - pattern: 'kafka.server<type=BrokerTopicMetrics, name=(.+)PerSec, topic=(.+)><>Count'
        name: kafka_server_brokertopicmetrics_$1_total
        type: COUNTER
        labels:
          topic: "$2"
      - pattern: 'kafka.server<type=BrokerTopicMetrics, name=(.+)PerSec><>Count'
        name: kafka_server_brokertopicmetrics_$1_total
        type: COUNTER
      - pattern: 'kafka.server<type=ReplicaManager, name=(.+)><>Value'
        name: kafka_server_replicamanager_$1
        type: GAUGE
      - pattern: 'kafka.controller<type=KafkaController, name=(.+)><>Value'
        name: kafka_controller_kafkacontroller_$1
        type: GAUGE
      - pattern: 'kafka.server<type=raft-metrics><>(current-state): (.+)'
        name: kafka_server_raft_state
        value: 1
        labels:
          state: "$2"
        type: GAUGE
