apiVersion: v1
kind: ConfigMap

metadata:
  name: nginx-html
  namespace: finops

data:
  index.html: |
    <!DOCTYPE html>
    <html lang="ru">
    <head>
      <meta charset="UTF-8">
      <title>FinOps Platform</title>
    </head>
    <body>
      <h1>FinOps Platform</h1>
      <p>Kubernetes работает.</p>
      <p>Домен: nginx.sniper541.com</p>
    </body>
    </html>
