apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-audit
  namespace: vault
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
